---
- hosts: webservers
  become: yes
  tasks:
    - name: this installs a package
      apt: name=apache2 update_cache=yes state=latest
      notify: enable apache
  handlers:
    - name: enable apache
      service: name=apache2 enabled=yes state=started
